### ISSUE TITLE
Confusing on Startup

### ISSUE THREAD

**Issue by ThomObarski** [christoomey/elm-reaction#1]
Would be nice to have a legend of the iconography to notate and discern emitter counts & obstacle types, either in a `help` or `rules` popup or visible either on first load or persistent somewhere on the page. 🗺

**Comment by christoomey** [comment]
Yep, seems true. Good points all around, Mr. Obarski.

**Comment by ThomObarski** [comment]
:coolala-thumbsup:

**Comment by christoomey** [comment]
Updates have been made. Confusion should be alleviated, insofar as possible.
